# Generated by Django 4.0.2 on 2022-02-17 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('talla', models.CharField(max_length=20)),
                ('precio_normal', models.IntegerField()),
                ('precio_oferta', models.IntegerField()),
                ('stock', models.IntegerField(default=1)),
                ('imagen', models.ImageField(upload_to='images/p/')),
                ('vigente', models.BooleanField(blank=True, default=True)),
                ('categoria', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='productos_app.categoria')),
            ],
        ),
    ]
