# Generated by Django 4.0.2 on 2022-03-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
