# Generated by Django 4.0.2 on 2022-02-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_normal', models.IntegerField()),
                ('precio_oferta', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='images')),
            ],
        ),
    ]
