# Generated by Django 4.0.2 on 2022-03-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0003_carrito_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(default=False),
        ),
    ]
